name: Review Approved
on:
  issues:
    types: ['labeled']

env:
  COMMIT_MSG: ${{ github.event.commits[0].message }}
  TRIGGERING_LABEL: ${{ github.event.label.name }}
  REVIEW_TEXT: ${{ github.event.issue.body }}
  REVIEW_TITLE: ${{ github.event.issue.title }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Check for 'review approved' issue label
        run: |
          echo "triggering label --> $TRIGGERING_LABEL"
          if [ $TRIGGERING_LABEL != "review approved" ]; then
            echo "Label is not 'review approved', exiting..."
            exit 1
          fi

      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: 'build'
      
      - name: Update site with new review
        run: |
          echo "creating post"
          FILENAME=$(date +%Y-%m-%d)-review.md
          echo $REVIEW_TEXT > build/_posts/$FILENAME
          echo "push to repo"
          git add build/_posts/$FILENAME
          git commit -m "added review $REVIEW_TITLE"
          git push -f